### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by limo1996** [limo1996/PiStudio#24]
Create logo and implement Saver.GetLogoAsync()

**Comment by theodorosploumis** [comment]
Hi, I could help with this if you like. I am not a logo designer but I like creating logos and graphics for open source projects. Are you still interested to this task? 

Thanks.

**Comment by limo1996** [comment]
Hi Theodoros,

thank you for your interest in my project. Yes, I am still interested in it. I would really appreciate that.
Thank you.

**Comment by theodorosploumis** [comment]
Here you are. I prefer most No1, 3 and 5. If the logos are not acceptable let me know so I design another proposal (mean that!) Thanks.

![pistudio_1-6](https://cloud.githubusercontent.com/assets/1315321/24579820/ac1a4c06-1705-11e7-8e02-ec7f22eb8e23.png)

**Comment by limo1996** [comment]
Thank you so much. They are all beautiful. I would choose 1, 3 and 5. Could you please change the color of these 3 logos. My app's main color is ARGB(255, 209, 52, 56). As border color in third image and second background(dark blue) in fifth image you can use ARGB(255, 31, 31, 31). The grey in fifth image is great. I will add you to contributors and you can upload images to PiStudio/PiStudio.Win10/Assets/ folder.. Thank you so much once again!

**Comment by theodorosploumis** [comment]
According to the new colors the logos will look like this. But the Light blue for border color does not a have a suitable contrast with the main gray color.

![proposals_b](https://cloud.githubusercontent.com/assets/1315321/24607069/c467b022-1878-11e7-9bfe-3129abc7b2a4.png)

**Comment by limo1996** [comment]
Hi there. I probably did not explain colors properly. I am sending you screenshot of the app. Main color is very similar to red.. Sorry for misunderstanding.. I would like to have logo mainly of this color.. 
<img width="591" alt="screenshot" src="https://cloud.githubusercontent.com/assets/11902085/24616132/879dedf6-1890-11e7-97db-b7b7a6480aa6.png">

Thank you for your patience.

**Comment by theodorosploumis** [comment]
Looks better now. B1 is the most suitable in my opinion but I am thinking if the border is useful when it comes to select the software on the MS dashboard, taskbar etc

![fixed_b1-3-5](https://cloud.githubusercontent.com/assets/1315321/24623895/b6e022ec-18b2-11e7-93c3-3ead1d9b6f4d.png)

**Comment by limo1996** [comment]
They are amazing... I think that I will use all three of them.. Please check logo dimensions in Win10 Assets folder. :)

**Comment by limo1996** [comment]
Thank You once again! Best luck..

**Comment by theodorosploumis** [comment]
Attaching the **svg logo** in case you need it. Also it's better to remove me from the collaborators. I could create pull requests if we need any modifications. Thank you too!

[pistudio_logo.svg.zip](https://github.com/limo1996/PiStudio/files/895506/pistudio_logo.svg.zip)
